In [23]:
import os
os.environ['CUDA_VISIBLE_DEVICES'] = "6,7"
import torch
import torch.nn as nn
import torch.optim as optim
from transformers import AutoModel, AutoTokenizer, pipeline, AutoModelForCausalLM
from swarm.optimizer.edge_optimizer.edge_network import EdgeNetwork
from swarm.optimizer.edge_optimizer.parameterization import EdgeWiseDistributionByModel
import pickle as pkl
import numpy as np

from swarm.llm.custom_llm import CustomLLM
from swarm.llm.format import Message

from vllm import LLM, SamplingParams

from experiments.evaluator.datasets.mmlu_dataset import MMLUDataset
import pickle

import asyncio
import json
from huggingface_hub import login 
login("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")

Token has not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /home/lucas/.cache/huggingface/token
Login successful


: 

In [2]:
with open("result/mmlu/mmlu_4true_4adv_MajorityVote_OptimizedSwarm.pkl", "rb") as f:
    swarm = pkl.load(f)

In [3]:
dataset_val = MMLUDataset('val')

Number of topics:  57
Total number of questions:  1531


In [4]:
def _print_conns(edge_probs: torch.Tensor, swarm):
    assert swarm is not None
    msgs = []
    for i_conn, (conn, prob) in enumerate(zip(
            swarm.connection_dist.potential_connections, edge_probs)):
        src_id, dst_id = conn
        src_node = swarm.composite_graph.find_node(src_id)
        dst_node = swarm.composite_graph.find_node(dst_id)
        msg = (f"{i_conn}: src={src_node.node_name}({src_node.id}), "
                f"dst={dst_node.node_name}({dst_node.id}), prob={prob.item():.3f}")
        msgs.append(msg+"\n")
        print(msg)

In [21]:

all_probs = []
for record in dataset_val:
    #print(record)
    input_dict = dataset_val.record_to_swarm_input(record)
    realized_graph, log_prob, log_probs = swarm.connection_dist.realize(swarm.composite_graph, inputs=input_dict)
    log_probs = torch.tensor(log_probs)
    #print(log_probs.shape)
    #print(swarm.connection_dist.potential_connections.shape)
    #print(log_probs)
    edge_probs = torch.sigmoid(torch.tensor(log_probs))
    all_probs.append(edge_probs)
all_probs = torch.stack(all_probs)

/tmp/ipykernel_1840106/2319829757.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  log_probs = torch.tensor(log_probs)
/tmp/ipykernel_1840106/2319829757.py:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  edge_probs = torch.sigmoid(torch.tensor(log_probs))


tensor([0.5867, 0.6451, 0.6064, 0.7099, 0.5270, 0.6821, 0.5284, 0.5644, 0.7003,
        0.6945, 0.5069, 0.6462, 0.6242, 0.6266, 0.7169, 0.6549, 0.6605, 0.6140,
        0.5160, 0.5265, 0.5401, 0.6707, 0.6287, 0.6715, 0.6923, 0.7072, 0.5078,
        0.6442, 0.5926, 0.5599, 0.6508, 0.6860, 0.5257, 0.7033, 0.7153, 0.7184,
        0.5212, 0.7266, 0.7139, 0.5040, 0.5053, 0.6958, 0.5647, 0.5096, 0.5082,
        0.7289, 0.7056, 0.6945, 0.5635, 0.5222, 0.5608, 0.5818, 0.5089, 0.6982,
        0.7176, 0.6204, 0.6906, 0.5126, 0.6910, 0.7095, 0.5081, 0.7119, 0.7147,
        0.5635])
tensor([4.8508e-05, 5.6911e-05, 6.5491e-05, 6.2954e-06, 1.6404e-05, 4.7740e-05,
        1.0013e-05, 9.7282e-05, 2.2213e-05, 7.6580e-05, 2.7849e-06, 1.1594e-04,
        1.1478e-04, 5.5585e-05, 3.8679e-06, 6.5268e-05, 3.7144e-05, 5.5966e-05,
        1.0170e-05, 1.5821e-05, 1.4250e-05, 2.5799e-05, 2.7562e-05, 3.7591e-05,
        3.5557e-05, 6.5965e-06, 1.9934e-06, 7.1506e-05, 7.6718e-05, 1.1822e-04,
        2.9111e-05, 1.6

In [22]:
print(all_probs[:][0])
all_probs_variance = torch.std(all_probs, dim=0)
print(all_probs_variance)
all_probs_mean = torch.mean(all_probs, dim=0)
print(all_probs_variance.shape)
print(all_probs_mean.shape)
print("Mean: ")
_print_conns(all_probs_mean, swarm)
print("Variance: ")
_print_conns(all_probs_variance, swarm)

tensor([0.5867, 0.6451, 0.6064, 0.7099, 0.5270, 0.6821, 0.5284, 0.5644, 0.7003,
        0.6945, 0.5069, 0.6462, 0.6242, 0.6266, 0.7169, 0.6549, 0.6605, 0.6140,
        0.5160, 0.5265, 0.5401, 0.6707, 0.6287, 0.6715, 0.6923, 0.7072, 0.5078,
        0.6442, 0.5926, 0.5599, 0.6508, 0.6860, 0.5257, 0.7033, 0.7153, 0.7184,
        0.5212, 0.7266, 0.7139, 0.5040, 0.5053, 0.6958, 0.5647, 0.5096, 0.5082,
        0.7289, 0.7056, 0.6945, 0.5635, 0.5222, 0.5608, 0.5818, 0.5089, 0.6982,
        0.7176, 0.6204, 0.6906, 0.5126, 0.6910, 0.7095, 0.5081, 0.7119, 0.7147,
        0.5635])
tensor([0.0070, 0.0075, 0.0081, 0.0025, 0.0041, 0.0069, 0.0032, 0.0099, 0.0047,
        0.0088, 0.0017, 0.0108, 0.0107, 0.0075, 0.0020, 0.0081, 0.0061, 0.0075,
        0.0032, 0.0040, 0.0038, 0.0051, 0.0052, 0.0061, 0.0060, 0.0026, 0.0014,
        0.0085, 0.0088, 0.0109, 0.0054, 0.0128, 0.0048, 0.0040, 0.0026, 0.0015,
        0.0023, 0.0008, 0.0021, 0.0008, 0.0016, 0.0037, 0.0055, 0.0014, 0.0013,
        0.0005, 0.0036,

In [ ]:
llm = LLM(model="google/gemma-7B-it", dtype="half", max_model_len=5888)

tokenizer = AutoTokenizer.from_pretrained("google/gemma-7B-it")

WARNING 03-23 15:06:50 config.py:618] Casting torch.bfloat16 to torch.float16.
INFO 03-23 15:06:50 llm_engine.py:87] Initializing an LLM engine with config: model='google/gemma-7B-it', tokenizer='google/gemma-7B-it', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=5888, download_dir=None, load_format=auto, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, seed=0)


In [ ]:
message = [{"role": "user", "content": "Write a poem about cats."}]
prompt = tokenizer.apply_chat_template(message, tokenize=False, add_generation_prompt=True)

sampling_params = SamplingParams(temperature=0.8, top_p=0.95, top_k=50,max_tokens=2000)
outputs = llm.generate(prompt,sampling_params=sampling_params)
# Print the outputs.
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.97s/it]

Prompt: '<bos><start_of_turn>user\nWrite a poem about cats.<end_of_turn>\n<start_of_turn>model\n', Generated text: "A purring ball of fluffy delight,\nWith eyes so bright, and full of light.\nSoft as velvet, gentle as snow,\nA heart of gold, a heart of gold.\n\nA ball of yarn, a playful toy,\nPounces and leaps, a merry joy.\nWith leaps and bounds, they dance with grace,\nA feline spirit, a wild, sweet space.\n\nFrom morning sun to evening stars,\nThey guard their homes, with watchful bars.\nA guardian spirit, a protector bold,\nWith love and loyalty, they unfold.\n\nThe heart of a lion, in a tiny frame,\nA guardian against danger's flame.\nWith a purr and a gentle head,\nThey bring joy, never to dread.\n\nSo let us cherish these precious souls,\nWith love and respect, they bring us gold.\nA gift from the heart, a furry friend,\nA purring companion, till the end."


In [ ]:
# pip install accelerate

tokenizer = AutoTokenizer.from_pretrained("google/gemma-7B-it")
#model = AutoModelForCausalLM.from_pretrained("google/gemma-7B-it",torch_dtype=torch.bfloat16).to("cuda")
model = AutoModelForCausalLM.from_pretrained("google/gemma-7B-it", torch_dtype=torch.bfloat16).to("cuda")



Loading checkpoint shards: 100%|██████████| 4/4 [00:01<00:00,  3.00it/s]


In [ ]:
#print(tokenizer.special_tokens_map)
#dummy message
message = [{"role": "user", "content": "Write a poem about cats."}]
prompt = tokenizer.apply_chat_template(message, tokenize=False, add_generation_prompt=True)
prompt = tokenizer.encode(prompt, add_special_tokens=False, return_tensors="pt").to("cuda")
prompt_len = len(prompt[0])
outputs = model.generate(
            prompt,
            do_sample=True,
            max_length=2000,
            top_k=50,
            top_p=1.0
        )
output_text = tokenizer.decode(outputs[0][prompt.shape[-1]:],skip_special_tokens=True)

In [ ]:
print(output_text)

A ball of fluff, with purrs so deep,
A heart of gold, a gentle leap.
Eyes that shine, a emerald glow,
A soul to love, forever more.

Soft steps in the night so bright,
A hunter's instinct, quick as light.
Pounce and play, a playful spark,
A lion's heart, in the smallest park.

A guardian's spirit, strong and true,
Protects their own, their family's too.
With love and grace, they fill the heart,
A furry friend, a gentle start.

So let us cherish these creatures sweet,
The purring joy that they complete.
For in their hearts, a treasure lies,
A bond beyond, a love that flies.


In [ ]:
# Create an instance of the GPTChat class
gpt_chat = CustomLLM()
#gpt_chat_2 = CustomLLM()

We are using custom LLM class
Load Model...
WARNING 03-23 15:16:01 config.py:618] Casting torch.bfloat16 to torch.float16.
INFO 03-23 15:16:01 llm_engine.py:87] Initializing an LLM engine with config: model='google/gemma-7B-it', tokenizer='google/gemma-7B-it', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=5888, download_dir=None, load_format=auto, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, seed=0)
INFO 03-23 15:16:05 weight_utils.py:163] Using model weights format ['*.safetensors']
INFO 03-23 15:16:09 llm_engine.py:357] # GPU blocks: 430, # CPU blocks: 585
INFO 03-23 15:16:11 model_runner.py:684] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 03-23 15:16:11 model_ru

In [ ]:

#if gpt_chat is gpt_chat_2:
#    print("Same instance")
# Create a list of Message objects
messages = [Message(role="user", content="What would a dog say if he could speak?")]
# Move messages to GPU
# Create tasks for the gen method
tasks = [asyncio.create_task(gpt_chat.agen(messages))]#, asyncio.create_task(gpt_chat_2.agen(messages))]

# Wait for the tasks to complete and get the results
results = [await task for task in tasks]

# Print the output
print(results)
#print(results[1])

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:07<00:00,  7.97s/it]

['A dog\'s spoken language would likely depend on the breed, individual personality, and training. However, some common sounds and phrases a dog might say if they could speak include:\n\n**Basic sounds:**\n\n* **Bark:** To warn of danger, protect their territory, or express excitement.\n* **Whine:** To express pain, discomfort, or submission.\n* **Growl:** To warn of threat, establish dominance, or protect themselves.\n* **Hiss:** To express fear, threat, or discomfort.\n* **Click:** To mark a positive behavior or to signal understanding.\n\n**Basic phrases:**\n\n* **"Woof!":** To greet people, express joy, or mark their presence.\n* **"Boo!":** To warn of danger or to startle someone.\n* **"Fetch!":** To invite play or to request a game.\n* **"Play!":** To express desire to play or have fun.\n* **"Treat!":** To signal that they want a treat.\n* **"Home!":** To signal that they want to go home.\n* **"Mine!":** To claim ownership of a toy or object.\n\n**More complex phrases:**\n\n* **"

: 

In [ ]:
potential_connections = [0 for _ in range(188)]
init_connection_probability = 0.1
domain = "crosswords"
llm_backbone_name="gpt2"

In [ ]:
swarm = Swarm(["CrosswordsReflection", "CrosswordsToT", "CrosswordsBruteForceOpt"], "crosswords", "gpt-3.5-turbo-1106", #"gpt-4-1106-preview"
            final_node_class="ReturnAll", 
            final_node_kwargs={},
            edge_optimize=True,
            init_connection_probability=init_connection_probability, 
            connect_output_nodes_to_final_node=connect_output_nodes_to_final_node, 
            include_inner_agent_connections=include_inner_agent_connections,
            edge_network_enable=edge_network_enable,
            llm_backbone_name=llm_backbone_name)

NameError: name 'Swarm' is not defined

In [ ]:
edge_network = EdgeNetwork(llm_backbone_name=llm_backbone_name, num_edges=len(potential_connections), initial_probability=init_connection_probability)
connection_dist = EdgeWiseDistributionByModel(potential_connections, edge_network, domain)

connection_dist.load_state_dict(torch.load("result/crosswords/experiment_edge_logits_10.pt"))

TypeError: 'int' object is not iterable

In [ ]:
# Create an instance of EdgeNetwork
num_edges = 188  # Replace with the number of edges used when saving the model
llm_backbone_name = 'gpt2'  # Replace with the name of the model used when saving the model
model = EdgeNetwork(llm_backbone_name, num_edges)

# Load the state dictionary
state_dict = torch.load('result/crosswords/experiment_edge_logits_10.pt')

# Remove 'model.' prefix from state dictionary keys and exclude 'order_params'
state_dict = {k.replace('model.', ''): v for k, v in state_dict.items() if k != 'model.order_params'}

model.load_state_dict(state_dict)

In [ ]:
# Create an instance of EdgeNetwork
num_edges = 188  # Replace with the number of edges used when saving the model
llm_backbone_name = 'gpt2'  # Replace with the name of the model used when saving the model
model = EdgeNetwork(llm_backbone_name, num_edges)

# Load the state dictionary
state_dict = torch.load('result/crosswords/experiment_edge_logits_10.pt')

# Remove 'model.' prefix from state dictionary keys
state_dict = {k.replace('model.', ''): v for k, v in state_dict.items()}

model.load_state_dict(state_dict)